name: Update Strava Heatmap

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-heatmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build Strava Heatmap
        run: |
          go build -o strava-heatmap ./cmd/strava-heatmap

      - name: Generate Heatmap SVG
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          # Save SVG output to a file
          ./strava-heatmap -generate > strava-heatmap.svg
          echo "Generated SVG file:"
          ls -la strava-heatmap.svg
      
      - name: Checkout profile repository
        uses: actions/checkout@v3
        with:
          repository: leesamuel423/leesamuel423
          path: profile
          token: ${{ secrets.PAT }}
      
      - name: Update README in profile repository
        run: |
          # Use the generated SVG file
          SVG_FILE="strava-heatmap.svg"
          
          if [ ! -f "$SVG_FILE" ]; then
            echo "ERROR: SVG file not found at $SVG_FILE"
            exit 1
          fi
          
          echo "Using SVG file: $SVG_FILE"
          
          # Check if the profile README has the markers
          if ! grep -q "<!-- STRAVA-HEATMAP-START -->" profile/README.md || ! grep -q "<!-- STRAVA-HEATMAP-END -->" profile/README.md; then
            echo "ERROR: Markers not found in profile README.md. Please add them first."
            echo "Add these lines to your profile README:"
            echo "<!-- STRAVA-HEATMAP-START -->"
            echo "<!-- STRAVA-HEATMAP-END -->"
            exit 1
          fi
          
          # Read and process the SVG content
          SVG_CONTENT=$(cat $SVG_FILE)
          
          # Ensure the SVG content has proper XML tags
          if ! grep -q "<svg" "$SVG_FILE"; then
            echo "ERROR: File does not appear to contain valid SVG content"
            head -n 20 "$SVG_FILE"
            exit 1
          fi
          
          # Create a temporary file
          TEMP_FILE=$(mktemp)
          
          # Process the README file in three parts: before markers, SVG content, after markers
          awk 'BEGIN{p=1}/<!-- STRAVA-HEATMAP-START -->/{print;p=0}p' profile/README.md > $TEMP_FILE
          echo "" >> $TEMP_FILE
          echo "$SVG_CONTENT" >> $TEMP_FILE
          echo "" >> $TEMP_FILE
          awk 'BEGIN{p=0}/<!-- STRAVA-HEATMAP-END -->/{p=1}p' profile/README.md >> $TEMP_FILE
          
          # Replace the original README with our modified version
          cp $TEMP_FILE profile/README.md
          
          # Commit and push the changes
          cd profile
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Strava activity heatmap [skip ci]"
          git push
