name: Update Strava Heatmap

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-heatmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build Strava Heatmap
        run: |
          go build -o strava-heatmap ./cmd/strava-heatmap

      - name: Update Heatmap
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          ./strava-heatmap -update

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "Update Strava activity heatmap [skip ci]"
            gh auth setup-git
            gh auth status
            git push origin main
          fi
