name: Update Strava Heatmap

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-heatmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build Strava Heatmap
        run: |
          go build -o strava-heatmap ./cmd/strava-heatmap

      - name: Generate Heatmap SVG
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          ./strava-heatmap -generate
          ls -la
      
      - name: Checkout profile repository
        uses: actions/checkout@v3
        with:
          repository: leesamuel423/leesamuel423
          path: profile
          token: ${{ secrets.PAT }}
      
      - name: Update README in profile repository
        run: |
          # Generate the SVG file
          ls -la
          
          # Extract SVG file path from the logs
          SVG_FILE=$(ls -t *.svg 2>/dev/null | head -1 || echo "")
          
          if [ -z "$SVG_FILE" ]; then
            echo "No SVG file found, checking if -generate created it in a different location"
            SVG_FILE=$(find . -name "*.svg" | head -1 || echo "")
            
            if [ -z "$SVG_FILE" ]; then
              echo "ERROR: No SVG file generated. Check the logs."
              exit 1
            fi
          fi
          
          echo "Found SVG file: $SVG_FILE"
          
          # Check if the profile README has the markers
          if ! grep -q "<!-- STRAVA-HEATMAP-START -->" profile/README.md || ! grep -q "<!-- STRAVA-HEATMAP-END -->" profile/README.md; then
            echo "ERROR: Markers not found in profile README.md. Please add them first."
            echo "Add these lines to your profile README:"
            echo "<!-- STRAVA-HEATMAP-START -->"
            echo "<!-- STRAVA-HEATMAP-END -->"
            exit 1
          fi
          
          # Create a temporary file
          TEMP_FILE=$(mktemp)
          
          # Process the README file in three parts: before markers, SVG content, after markers
          sed -n '1,/<!-- STRAVA-HEATMAP-START -->/p' profile/README.md > $TEMP_FILE
          echo -e "\n" >> $TEMP_FILE
          cat $SVG_FILE >> $TEMP_FILE
          echo -e "\n" >> $TEMP_FILE
          sed -n '/<!-- STRAVA-HEATMAP-END -->/,$p' profile/README.md >> $TEMP_FILE
          
          # Replace the original README with our modified version
          cp $TEMP_FILE profile/README.md
          
          # Commit and push the changes
          cd profile
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Strava activity heatmap [skip ci]"
          git push
